### ISSUE TITLE
Question: is the module compatible with amd/requirejs ?

### ISSUE THREAD

**Issue by suryagh** [krakenjs/beaver-logger#1]
Can  `beaver-logger` module be loaded using [requireJS](http://requirejs.org/) on the client side? 

I [see](https://github.com/krakenjs/beaver-logger/blob/master/dist/beaver-logger.js#L4) there is a check for `amd`, but wanted to check if someone was successful loading this on the browser using `requireJS module loader`, since I'm getting `$logger` not defined on the client side. 

Link to any `repo` that uses `beaver-logger` with `requireJS` would be very helpful if one exist.

**Comment by suryagh** [comment]
Here is the [jsfiddle](http://jsfiddle.net/danpan/qc10sehq/) to reproduce the issue. 
I also tried various other combinations, like, with `shim` configuration but no luck.

**Comment by bluepnume** [comment]
Hmm weird. We're using webpack's umd output, but I haven't experimented much with amd. I'll take a look.

**Comment by bluepnume** [comment]
Managed to get it working -- http://jsfiddle.net/qc10sehq/27/

Please let me know if this works for you.

**Comment by suryagh** [comment]
That worked. Thank you!
