### ISSUE TITLE
Problem with zalgo-promise

### ISSUE THREAD

**Issue by oscarcalvo** [krakenjs/beaver-logger#15]
Hi:

I cant use this library now. It have worked until five days ago but now it throws an error like this

Uncaught TypeError: Cannot read property 'push' of undefined
    at t (exceptions.js:22)
    at Function.e.onPossiblyUnhandledException (promise.js:362)
    at Object../src/index.js (setup.js:32)
    at n (bootstrap 17df07d1c18588f01490:19)
    at Object../src/load.js (load.js:26)
    at n (bootstrap 17df07d1c18588f01490:19)
    at ./node_modules/Base64/base64.js (bootstrap 17df07d1c18588f01490:62)
    at bootstrap 17df07d1c18588f01490:62

I use it as client logger in a front application where I am using paypal integration for payments as well. And paypal button fails as well before of render.
I think both of them are loading zalgo-promise and it uses a object in global. Anyone more with this issue?

**Comment by bluepnume** [comment]
What environment are you running in? In a client-side browser?

**Comment by oscarcalvo** [comment]
yes it is. You can check error here: http://preproduction.babelic.com/ it is shown in load in console

**Comment by bluepnume** [comment]
Thanks for the link! I think I narrowed down the cause, can you try with the latest version?

**Comment by oscarcalvo** [comment]
are you speaking about latests version of zalgo-promise arent you? i have updated and uploaded to previous link but error is still there

**Comment by oscarcalvo** [comment]
Hi @bluepnume any news about that? thanks

**Comment by bluepnume** [comment]
@oscarcalvo -- I've just published a new version of beaver-logger, using the updated zalgo promise. Can you try upgrading that too?

**Comment by oscarcalvo** [comment]
its working now, thanks a lot.
