### ISSUE TITLE
Question: is `beaver-logger` compatible with the lusca's csrf check?

### ISSUE THREAD

**Issue by suryagh** [krakenjs/beaver-logger#3]
`beaver-logger` seems to make an `ajax-post` to send the logs to the server. This `post` method type is hard-coded, and is failing when **kraken's lusca** middleware is enabled with `csrf` check. 

Probably, there should be a way to pass-in the `csrf` token to the `beaver-logger` which in turn will get added as `['XSRF-TOKEN']` `header` of the `post` request?

**Comment by bluepnume** [comment]
Good thought. I'm thinking it would be good to have a `buildCustomHeaders()` to pass in whatever headers are needed.

**Comment by bluepnume** [comment]
Here we go! https://github.com/krakenjs/beaver-logger#loggeraddheaderbuilderfunction

**Comment by suryagh** [comment]
Awesome! Thank you.I will test this on Monday.
