### ISSUE TITLE
Create CHANGELOG.md [Hacktoberfest]

### ISSUE THREAD

**Issue by Cijin** [krakenjs/beaver-logger#42]
* Create a change log using the format from [keep a changelog](https://keepachangelog.com/en/1.0.0/)
* Update changelog with last three or four commits

* For future use, update changelog when making changes to the repository
* Changelog can also be used to keep track of unreleased files

**Comment by songz** [comment]
please close : https://github.com/krakenjs/beaver-logger/pull/41
