### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by Shift1N** [krakenjs/beaver-logger#45]
I have been trying to get the demo set up for beaver-logger and I keep running into this error during the webpack step:

`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list`

I have tried editing the package.json with no avail, this is currently what it is:

`"webpack": "babel-node --config-file ./node_modules/grumbler-scripts/config/.babelrc-node --plugins=transform-es2015-modules-commonjs ./node_modules/.bin/webpack --display-optimization-bailout --progress",`

Any help or guidance would be much appreciated.

**Comment by mnicpt** [comment]
@Shift1N I just ran through the setup defined in the README under the `/demo` and everything looks to be working ok.  I would recommend running `npm run reinstall` after doing a `git pull` and then go back through the setup in the README mentioned above and see if that fixes the issue you were seeing.  Please let me know if this fixes it.

**Comment by mnicpt** [comment]
@Shift1N Were you able to resolve?

**Comment by mnicpt** [comment]
@Shift1N Closing ticket.  If this is still a problem, let me know.
